#!/usr/bin/python

from bugzilla.agents import BMOAgent
#from bugzilla.utils import get_credentials

if __name__ == '__main__':
    #username, password = get_credentials()
    username = 'szchen@mozilla.com'
    bmo = BMOAgent(username, None)

    options = {
        'email1':             username,
        'email1_assigned_to': 1,
        'status':             'NEW'
    }

    buglist = bmo.get_bug_list(options)
    for bug in buglist:
        print bug
