#!/bin/bash

commit=`hg qseries`
if [ "$commit" != "" ]; then
  hg qpop -a
  hg qseries | cut -b 1 | tac | xargs hg qremove
fi

hg pull -u

hg qimport ../gecko-dev/patch/*
hg qpush -a
hg addalltry
hg try
