#!/bin/bash

# Usage: omni_push.sh <target_filename>
if [ $# -eq "0" ] ; then
  echo "Usage: $0 <target_filename>"
  exit 1
fi

# Make sure the device is connected.
remount_msg=`adb remount 2>&1`
if [ "$remount_msg" != "remount succeeded" ] ; then
  echo $remount_msg
  exit 1
fi

# Make sure the target file exists.
for file in "$@"
do
  if [ -f $file ] ; then
    target="*$file*"
  else
    echo "Error: $file not exists"
    exit 1
  fi
done

# Work in a tmp folder.
tmp_folder=`uuidgen | cut -d'-' -f 1`
mkdir $tmp_folder
cd $tmp_folder

# Extract the target file.
adb pull /system/b2g/omni.ja &> /dev/null
unzip omni.ja &> /dev/null

for file in "$@"
do
  # Overwrite the target file.
  target_path=`find -name $target`
  cd ..
  cp $file $tmp_folder/$target_path
  cd $tmp_folder
  rm omni.ja
  zip -r omni.ja * &> /dev/null
done

# Push and reboot.
adb push omni.ja /system/b2g &> /dev/null
adb shell stop b2g
adb shell start b2g

# Clear the stuff.
cd ..
rm -rf $tmp_folder
